/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Open KPIs",
  "url": "https://devyendarm.github.io",
  "baseUrl": "/",
  "trailingSlash": false,
  "onBrokenLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "devyendarm",
  "projectName": "OpenKPIs",
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "docs/kpis",
          "routeBasePath": "docs",
          "sidebarPath": "C:\\Users\\mdevy\\OneDrive\\Projects\\OpenKPIs\\git_repo\\openkpis-starter\\sidebars.kpis.js"
        },
        "blog": false,
        "theme": {
          "customCss": "C:\\Users\\mdevy\\OneDrive\\Projects\\OpenKPIs\\git_repo\\openkpis-starter\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "scripts": [
    {
      "src": "/js/copy-code.js?v=9",
      "async": true
    },
    {
      "src": "/js/github-signin-mount.js?v=4",
      "async": false
    }
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "dimensions",
        "path": "docs/dimensions",
        "routeBasePath": "dimensions",
        "sidebarPath": "C:\\Users\\mdevy\\OneDrive\\Projects\\OpenKPIs\\git_repo\\openkpis-starter\\sidebars.dimensions.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "events",
        "path": "docs/events",
        "routeBasePath": "events",
        "sidebarPath": "C:\\Users\\mdevy\\OneDrive\\Projects\\OpenKPIs\\git_repo\\openkpis-starter\\sidebars.events.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "metrics",
        "path": "docs/metrics",
        "routeBasePath": "metrics",
        "sidebarPath": "C:\\Users\\mdevy\\OneDrive\\Projects\\OpenKPIs\\git_repo\\openkpis-starter\\sidebars.metrics.js"
      }
    ]
  ],
  "themeConfig": {
    "metadata": [
      {
        "name": "keywords",
        "content": "KPI, analytics, metrics, data analysis, business intelligence, open source, GA4, Adobe Analytics, Amplitude"
      },
      {
        "name": "author",
        "content": "OpenKPIs Team"
      },
      {
        "name": "robots",
        "content": "index, follow"
      },
      {
        "name": "viewport",
        "content": "width=device-width, initial-scale=1.0"
      }
    ],
    "navbar": {
      "title": "OpenKPIs",
      "items": [
        {
          "to": "/docs",
          "label": "KPIs",
          "position": "left"
        },
        {
          "to": "/dimensions",
          "label": "Dimensions",
          "position": "left"
        },
        {
          "to": "/events",
          "label": "Events",
          "position": "left"
        },
        {
          "to": "/metrics",
          "label": "Metrics",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "Industries",
          "position": "left",
          "items": [
            {
              "label": "Retail",
              "to": "/docs?industry=retail"
            },
            {
              "label": "SaaS",
              "to": "/docs?industry=saas"
            },
            {
              "label": "E-commerce",
              "to": "/docs?industry=ecommerce"
            },
            {
              "label": "Healthcare",
              "to": "/docs?industry=healthcare"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Categories",
          "position": "left",
          "items": [
            {
              "label": "Conversion",
              "to": "/docs?category=conversion"
            },
            {
              "label": "Revenue",
              "to": "/docs?category=revenue"
            },
            {
              "label": "Engagement",
              "to": "/docs?category=engagement"
            },
            {
              "label": "Retention",
              "to": "/docs?category=retention"
            }
          ]
        },
        {
          "type": "html",
          "position": "right",
          "value": "<input type=\"text\" placeholder=\"Search\" style=\"padding: 0.4rem 0.6rem; border: 1px solid var(--ifm-color-emphasis-300); border-radius: 4px; font-size: 0.85rem; width: 120px; background-color: var(--ifm-background-color); color: var(--ifm-font-color-base); outline: none;\" onkeypress=\"if(event.key==='Enter'){var b=(window.__docusaurus&&window.__docusaurus.baseUrl)||'/'; window.location.href=b+'search?q='+encodeURIComponent(this.value)}\" />"
        },
        {
          "type": "html",
          "position": "right",
          "value": "<div id=\"github-signin-root\" style=\"display: inline-block; margin: 0 0.5rem;\"></div>"
        },
        {
          "href": "https://github.com/devyendarm/OpenKPIs",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
